- name: ansible setup | ensure ansible is the latest version
  tags: ansible,ansible-setup
  package:
    name: ansible
    state: latest

- name: ansible setup | install required packages
  tags: ansible,ansible-setup,packages
  package:
    name:
      #- acl
      - python3-psutil


- name: ansible setup | create ansible log file
  tags: ansible,ansible-setup
  file:
    path: /var/log/ansible.log
    owner: root
    group: root
    mode: 0664
    state: touch
  changed_when: False

- name: ansible setup | add logrotate for ansible log file
  tags: ansible-setup
  copy:
    src: files/ansible_setup/logrotate
    dest: /etc/logrotate.d/ansible
    owner: root
    group: root
    mode: 0644
