# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yaml"
  tags: always

- block:
  # Set up ansible
  - import_tasks: ansible_setup.yaml

  # Set up local install (bin/etc/share) directory
  - import_tasks: local/linux_local.yaml

  # Manage packages
  - import_tasks: packages/dev.yaml
  - import_tasks: packages/utils.yaml

  # Admin tasks
  - import_tasks: admin/journalctl.yaml
  - import_tasks: admin/hosts.yaml

  rescue:
    - set_fact: task_failed=true
