- name: admin | journalctl | adjust retention period
  tags: admin,systemd,journal,journald,sysctl
  lineinfile:
    dest: "/etc/systemd/journald.conf"
    regexp: "^#MaxFileSec="
    line: "MaxFileSec=10day"
  register: journald_config

- name: admin | journalctl | restart journald (config changed)
  service:
    name: systemd-journald
    state: restarted
  when: journald_config.changed
